import { IOption } from "@/types/GlobalTypes"

export const PGCourseSubTypeList: IOption[] = [
  { id: "DM/MCh", text: "DM / MCh" },
  { id: "DNB", text: "DNB" },
  { id: "DNB-Diploma", text: "DNB-Diploma" },
  { id: "MD/MS/Diploma", text: "MD / MS / Diploma" },
  { id: "MD/MSAyurveda", text: "MD / MS Ayurveda" },
  { id: "MDHomeopathy", text: "MMD Homeopathy" },
  { id: "MDS", text: "MDS" },
]

export const states = [
  { id: 1, text: "Andaman And Nicobar" },
  { id: 2, text: "Andhra Pradesh" },
  { id: 3, text: "Arunachal Pradesh" },
  { id: 4, text: "Assam" },
  { id: 5, text: "Bihar" },
  { id: 6, text: "Chandigarh" },
  { id: 7, text: "Chhattisgarh" },
  { id: 8, text: "Dadra and Nagar Haveli" },
  { id: 9, text: "Daman and Diu" },
  { id: 37, text: "Delhi" },
  { id: 10, text: "Goa" },
  { id: 11, text: "Gujarat" },
  { id: 12, text: "Haryana" },
  { id: 13, text: "Himachal Pradesh" },
  { id: 14, text: "Jammu and Kashmir" },
  { id: 15, text: "Jharkhand" },
  { id: 16, text: "Karnataka" },
  { id: 17, text: "Kerala" },
  { id: 18, text: "Ladakh" },
  { id: 19, text: "Lakshadweep" },
  { id: 20, text: "Madhya Pradesh" },
  { id: 21, text: "Maharashtra" },
  { id: 22, text: "Manipur" },
  { id: 23, text: "Meghalaya" },
  { id: 24, text: "Mizoram" },
  { id: 25, text: "Nagaland" },
  { id: 26, text: "Odisha" },
  { id: 27, text: "Pondicherry" },
  { id: 28, text: "Punjab" },
  { id: 29, text: "Rajasthan" },
  { id: 30, text: "Sikkim" },
  { id: 31, text: "Tamil Nadu" },
  { id: 32, text: "Telangana" },
  { id: 33, text: "Tripura" },
  { id: 34, text: "Uttar Pradesh" },
  { id: 35, text: "Uttarakhand" },
  { id: 36, text: "West Bengal" },
   
  
]

export const closingRanksStates = [
  { id: 37, text: "Central" },
  ...states?.slice(1),
]

export const courses = [
  { id: 0, text: "MD" },
  { id: 1, text: "MS" },
  { id: 2, text: "MDS" },
  { id: 3, text: "MBBS" },
  { id: 4, text: "BDS" },
]

export const courseType = [
  { id: "ug", text: "UG" },
  { id: "pg", text: "PG" },
]

export const categories = [
  { id: 0, text: "General" },
  { id: 1, text: "General-EWS" },
  { id: 2, text: "EWS" },
  { id: 3, text: "EWS-PwD" },
  { id: 4, text: "OBC" },
  { id: 5, text: "OBC-PwD" },
  { id: 6, text: "Open" },
  { id: 7, text: "Open-PwD" },
  { id: 8, text: "SC" },
  { id: 9, text: "SC-PwD" },
  { id: 10, text: "ST" },
  { id: 11, text: "ST-PwD" },
]

export const instituteTypes = [
  { id: 0, text: "DEEMED" },
  { id: 1, text: "PRIVATE" },
  { id: 2, text: "PRIVATE UNIVERSITY" },
  { id: 3, text: "GOVERNMENT" },
]
export const stateInstituteTypes = [
  { id: 1, text: "PRIVATE" },
  { id: 2, text: "PRIVATE UNIVERSITY" },
  { id: 3, text: "GOVERNMENT" },
]
export const allInstituteTypes = (courseType:string|null)=>{
  return[
 
  { id:1, text: "GOVERNMENT"},
  ...[(courseType&&courseType=="DNB"? { id: 2, text: "PRIVATE" }:{ id: 3, text: "DEEMED" })]
]}

export function years(): IOption[] {
  const yearsArr: IOption[] = []

  for (let i = 0; i < 28; i++) {
    yearsArr.push({
      id: String(2023 + i),
      text: String(2023 + i),
    })
  }

  return yearsArr
}

export function configYearOptions(): IOption[] {
  const yearsArr: IOption[] = []

  for (let i = 0; i < 27; i++) {
    yearsArr.push({
      id: `${String(2023 + i)} - ${String(2024 + i)}`,
      text: `${String(2023 + i)} - ${String(2024 + i)}`,
    })
  }

  return yearsArr
}

export const quotas = [
  {
    id: 169,
    text: "AIIMS - Foreign Nationals",
  },
  {
    id: 149,
    text: "AIIMS - Open",
  },
  {
    id: 148,
    text: "All India Quota",
  },
  {
    id: 150,
    text: "AMU - Internal",
  },
  {
    id: 151,
    text: "AMU - NRI",
  },
  {
    id: 152,
    text: "AMU - Open",
  },
  {
    id: 153,
    text: "BHU - Open",
  },
  {
    id: 154,
    text: "CW of Armed Forces Personnel",
  },
  {
    id: 160,
    text: "Deemed - Jain Minority",
  },
  {
    id: 165,
    text: "Deemed - Muslim Minority",
  },
  {
    id: 168,
    text: "Deemed - NRI",
  },
  {
    id: 166,
    text: "Deemed - Paid Seats (PS)",
  },
  {
    id: 214,
    text: "Delhi Univ - Delhi CW",
  },
  {
    id: 155,
    text: "Delhi Univ - DU Quota (State)",
  },
  {
    id: 156,
    text: "ESI - Insured Persons",
  },
  {
    id: 215,
    text: "IP Univ - Delhi CW",
  },
  {
    id: 157,
    text: "IP Univ - IP Quota (State)",
  },
  {
    id: 159,
    text: "Jamia - Internal",
  },
  {
    id: 161,
    text: "Jamia - Muslim",
  },
  {
    id: 167,
    text: "Jamia - Muslim Women",
  },
  {
    id: 164,
    text: "Jamia - Open",
  },
  {
    id: 163,
    text: "JIPMER - NRI",
  },
  {
    id: 162,
    text: "JIPMER - Open",
  },
  {
    id: 158,
    text: "JIPMER - Pondicherry Domicile",
  },
]


export const paymentType = {
  SINGLE_COLLEGE_CLOSING_RANK: "SINGLE_COLLEGE_CLOSING_RANK",
  STATE_CLOSING_RANK: "STATE_CLOSING_RANK",
  ALL_INDIA_CLOSING_RANK: "ALL_INDIA_CLOSING_RANK",

  PREMIUM_PLAN: "PREMIUM_PLAN",
  COLLEGE_CUT_OFF: "COLLEGE_CUT_OFF",
  RANK_COLLEGE_PREDICTOR: "RANK_COLLEGE_PREDICTOR",
}

export const priceType = {
  COLLEGE_CUT_OFF_UG: "College Cutoff - UG",
  COLLEGE_CUT_OFF_MDS: "College Cutoff - MDS",
  COLLEGE_CUT_OFF_PG: "College Cutoff - PG",
  COLLEGE_CUT_OFF_SS: "College Cutoff - SS",
  COLLEGE_CUT_OFF_DNB: "College Cutoff - DNB",
  COLLEGE_CUT_OFF_INICET: "College Cutoff - INICET",
  COLLEGE_CUT_OFF_AIAPGET: "College Cutoff - AIAPGET",
  
  ALL_INDIA_COLLEGE_CUT_OFF_UG: "All India College Cutoff - UG",
  ALL_INDIA_COLLEGE_CUT_OFF_MDS: "All India College Cutoff - MDS",
  ALL_INDIA_COLLEGE_CUT_OFF_PG: "All India College Cutoff - PG",
  ALL_INDIA_COLLEGE_CUT_OFF_SS: "All India College Cutoff - SS",
  ALL_INDIA_COLLEGE_CUT_OFF_DNB: "All India College Cutoff - DNB",
  ALL_INDIA_COLLEGE_CUT_OFF_INICET: "All India College Cutoff - INICET",
  ALL_INDIA_COLLEGE_CUT_OFF_AIAPGET: "All India College Cutoff - AIAPGET",

  RANK_COLLEGE_PREDICTOR: "College Predictor",
  
// UG
 ALL_INDIA_COLLEGE_PREDICTOR_UG_MBBS: "All India College Predictor-UG-MBBS",
 ALL_INDIA_COLLEGE_PREDICTOR_UG_BDS: "All India College Predictor-UG-BDS",
 ALL_INDIA_COLLEGE_PREDICTOR_UG_BAMS: "All India College Predictor-UG-BAMS",
 ALL_INDIA_COLLEGE_PREDICTOR_UG_BHMS: "All India College Predictor-UG-BHMS",

 STATE_COLLEGE_PREDICTOR_UG_MBBS: "State College Predictor-UG-MBBS",
 STATE_COLLEGE_PREDICTOR_UG_BDS: "State College Predictor-UG-BDS",
 STATE_COLLEGE_PREDICTOR_UG_BAMS: "State College Predictor-UG-BAMS",
 STATE_COLLEGE_PREDICTOR_UG_BHMS: "State College Predictor-UG-BHMS",

// PG
 ALL_INDIA_COLLEGE_PREDICTOR_PG_ALL: "All India College Predictor-PG-ALL",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_DERMATOLOGY: "All India College Predictor-PG-MD-DERMATOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MS_ORTHOPEDICS: "All India College Predictor-PG-MS-ORTHOPEDICS",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_PHARMACOLOGY: "All India College Predictor-PG-MD-PHARMACOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MS_OBS_AND_GYNAE: "All India College Predictor-PG-MS-OBS-AND-GYNAE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_PATHOLOGY: "All India College Predictor-PG-MD-PATHOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MS_GENERAL_SURGERY: "All India College Predictor-PG-MS-GENERAL-SURGERY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_PAEDIATRICS: "All India College Predictor-PG-MD-PAEDIATRICS",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_GENERAL_MEDICINE: "All India College Predictor-PG-MD-GENERAL-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_ANATOMY: "All India College Predictor-PG-MD-ANATOMY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_COMMUNITY_MEDICINE: "All India College Predictor-PG-MD-COMMUNITY-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_PHYSIOLOGY: "All India College Predictor-PG-MD-PHYSIOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_BIOCHEMISTRY: "All India College Predictor-PG-MD-BIOCHEMISTRY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_MICROBIOLOGY: "All India College Predictor-PG-MD-MICROBIOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_TB_AND_CHEST: "All India College Predictor-PG-MD-TB-AND-CHEST",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_RADIOLOGY: "All India College Predictor-PG-MD-RADIOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_PSYCHIATRY: "All India College Predictor-PG-MD-PSYCHIATRY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_EMERGENCY_MEDICINE: "All India College Predictor-PG-MD-EMERGENCY-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MS_OPHTHALMOLOGY: "All India College Predictor-PG-MS-OPHTHALMOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MS_ENT: "All India College Predictor-PG-MS-ENT",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_ANAESTHESIA: "All India College Predictor-PG-MD-ANAESTHESIA",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_FORENSIC_MEDICINE: "All India College Predictor-PG-MD-FORENSIC-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_NUCLEAR_MEDICINE: "All India College Predictor-PG-MD-NUCLEAR-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_RADIOTHERAPY: "All India College Predictor-PG-MD-RADIOTHERAPY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_PMR: "All India College Predictor-PG-MD-PMR",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_GERIATRIC: "All India College Predictor-PG-MD-GERIATRIC",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_PALLIATIVE_MEDICINE: "All India College Predictor-PG-MD-PALLIATIVE-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MPH_EPIDEIMOLOGY: "All India College Predictor-PG-MPH-EPIDEIMOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_PAEDIATRICS: "All India College Predictor-PG-DIPLOMA-IN-PAEDIATRICS",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_TRANSFUSION_MEDICINE: "All India College Predictor-PG-MD-TRANSFUSION-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_ANAESTHESIA: "All India College Predictor-PG-DIPLOMA-IN-ANAESTHESIA",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_ORTHOPAEDICS: "All India College Predictor-PG-DIPLOMA-IN-ORTHOPAEDICS",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_OBS_AND_GYNAE: "All India College Predictor-PG-DIPLOMA-IN-OBS-AND-GYNAE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_SPORTS_MEDICINE: "All India College Predictor-PG-MD-SPORTS-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_OPHTHALMOLOGY: "All India College Predictor-PG-DIPLOMA-IN-OPHTHALMOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_PATHOLOGY: "All India College Predictor-PG-DIPLOMA-IN-PATHOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_TROPICAL_MEDICINE: "All India College Predictor-PG-MD-TROPICAL-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_LABORATORY_MEDICINE: "All India College Predictor-PG-MD-LABORATORY-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_FAMILY_MEDICINE: "All India College Predictor-PG-MD-FAMILY-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_HOSPITAL_ADMINISTRATION: "All India College Predictor-PG-MD-HOSPITAL-ADMINISTRATION",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_PSYCHIATRY: "All India College Predictor-PG-DIPLOMA-IN-PSYCHIATRY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_FORENSIC_MEDICINE: "All India College Predictor-PG-DIPLOMA-IN-FORENSIC-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_ENT: "All India College Predictor-PG-DIPLOMA-IN-ENT",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_DERMATOLOGY: "All India College Predictor-PG-DIPLOMA-IN-DERMATOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_RADIATION_MEDICINE: "All India College Predictor-PG-DIPLOMA-IN-RADIATION-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MS_TRAUMATOLOGY_AND_SURGERY: "All India College Predictor-PG-MS-TRAUMATOLOGY-AND-SURGERY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_RADIOTHERAPY: "All India College Predictor-PG-DIPLOMA-IN-RADIOTHERAPY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_RADIOLOGY: "All India College Predictor-PG-DIPLOMA-IN-RADIOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_PUBLIC_HEALTH: "All India College Predictor-PG-DIPLOMA-IN-PUBLIC-HEALTH",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_TB_AND_CHEST: "All India College Predictor-PG-DIPLOMA-IN-TB-AND-CHEST",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_DIABETOLOGY: "All India College Predictor-PG-DIPLOMA-IN-DIABETOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_SPORTS_MEDICINE: "All India College Predictor-PG-DIPLOMA-IN-SPORTS-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_BACTERIOLOGY: "All India College Predictor-PG-DIPLOMA-IN-BACTERIOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_TRANSFUSION_MEDICINE: "All India College Predictor-PG-DIPLOMA-IN-TRANSFUSION-MEDICINE",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MCH_NEURO_SURGERY: "All India College Predictor-PG-MCH-NEURO-SURGERY",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_MD_COMMUNITY_HEALTH_ADMINSTRATION: "All India College Predictor-PG-MD-COMMUNITY-HEALTH-ADMINSTRATION",
 ALL_INDIA_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_HEALTH_ADMINISTRATION: "All India College Predictor-PG-DIPLOMA-IN-HEALTH-ADMINISTRATION",
 
 
 
STATE_COLLEGE_PREDICTOR_PG_ALL: "State College Predictor-PG-ALL",

STATE_COLLEGE_PREDICTOR_PG_MD_DERMATOLOGY: "State College Predictor-PG-MD-DERMATOLOGY",
STATE_COLLEGE_PREDICTOR_PG_MS_ORTHOPEDICS: "State College Predictor-PG-MS-ORTHOPEDICS",
STATE_COLLEGE_PREDICTOR_PG_MD_PHARMACOLOGY: "State College Predictor-PG-MD-PHARMACOLOGY",
STATE_COLLEGE_PREDICTOR_PG_MS_OBS_AND_GYNAE: "State College Predictor-PG-MS-OBS-AND-GYNAE",
STATE_COLLEGE_PREDICTOR_PG_MD_PATHOLOGY: "State College Predictor-PG-MD-PATHOLOGY",
STATE_COLLEGE_PREDICTOR_PG_MS_GENERAL_SURGERY: "State College Predictor-PG-MS-GENERAL-SURGERY",
STATE_COLLEGE_PREDICTOR_PG_MD_PAEDIATRICS: "State College Predictor-PG-MD-PAEDIATRICS",
STATE_COLLEGE_PREDICTOR_PG_MD_GENERAL_MEDICINE: "State College Predictor-PG-MD-GENERAL-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MD_ANATOMY: "State College Predictor-PG-MD-ANATOMY",
STATE_COLLEGE_PREDICTOR_PG_MD_COMMUNITY_MEDICINE: "State College Predictor-PG-MD-COMMUNITY-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MD_PHYSIOLOGY: "State College Predictor-PG-MD-PHYSIOLOGY",
STATE_COLLEGE_PREDICTOR_PG_MD_BIOCHEMISTRY: "State College Predictor-PG-MD-BIOCHEMISTRY",
STATE_COLLEGE_PREDICTOR_PG_MD_MICROBIOLOGY: "State College Predictor-PG-MD-MICROBIOLOGY",
STATE_COLLEGE_PREDICTOR_PG_MD_TB_AND_CHEST: "State College Predictor-PG-MD-TB-AND-CHEST",
STATE_COLLEGE_PREDICTOR_PG_MD_RADIOLOGY: "State College Predictor-PG-MD-RADIOLOGY",
STATE_COLLEGE_PREDICTOR_PG_MD_PSYCHIATRY: "State College Predictor-PG-MD-PSYCHIATRY",
STATE_COLLEGE_PREDICTOR_PG_MD_EMERGENCY_MEDICINE: "State College Predictor-PG-MD-EMERGENCY-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MS_OPHTHALMOLOGY: "State College Predictor-PG-MS-OPHTHALMOLOGY",
STATE_COLLEGE_PREDICTOR_PG_MS_ENT: "State College Predictor-PG-MS-ENT",
STATE_COLLEGE_PREDICTOR_PG_MD_ANAESTHESIA: "State College Predictor-PG-MD-ANAESTHESIA",
STATE_COLLEGE_PREDICTOR_PG_MD_FORENSIC_MEDICINE: "State College Predictor-PG-MD-FORENSIC-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MD_NUCLEAR_MEDICINE: "State College Predictor-PG-MD-NUCLEAR-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MD_RADIOTHERAPY: "State College Predictor-PG-MD-RADIOTHERAPY",
STATE_COLLEGE_PREDICTOR_PG_MD_PMR: "State College Predictor-PG-MD-PMR",
STATE_COLLEGE_PREDICTOR_PG_MD_GERIATRIC: "State College Predictor-PG-MD-GERIATRIC",
STATE_COLLEGE_PREDICTOR_PG_MD_PALLIATIVE_MEDICINE: "State College Predictor-PG-MD-PALLIATIVE-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MPH_EPIDEIMOLOGY: "State College Predictor-PG-MPH-EPIDEIMOLOGY",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_PAEDIATRICS: "State College Predictor-PG-DIPLOMA-IN-PAEDIATRICS",
STATE_COLLEGE_PREDICTOR_PG_MD_TRANSFUSION_MEDICINE: "State College Predictor-PG-MD-TRANSFUSION-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_ANAESTHESIA: "State College Predictor-PG-DIPLOMA-IN-ANAESTHESIA",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_ORTHOPAEDICS: "State College Predictor-PG-DIPLOMA-IN-ORTHOPAEDICS",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_OBS_AND_GYNAE: "State College Predictor-PG-DIPLOMA-IN-OBS-AND-GYNAE",
STATE_COLLEGE_PREDICTOR_PG_MD_SPORTS_MEDICINE: "State College Predictor-PG-MD-SPORTS-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_OPHTHALMOLOGY: "State College Predictor-PG-DIPLOMA-IN-OPHTHALMOLOGY",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_PATHOLOGY: "State College Predictor-PG-DIPLOMA-IN-PATHOLOGY",
STATE_COLLEGE_PREDICTOR_PG_MD_TROPICAL_MEDICINE: "State College Predictor-PG-MD-TROPICAL-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MD_LABORATORY_MEDICINE: "State College Predictor-PG-MD-LABORATORY-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MD_FAMILY_MEDICINE: "State College Predictor-PG-MD-FAMILY-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MD_HOSPITAL_ADMINISTRATION: "State College Predictor-PG-MD-HOSPITAL-ADMINISTRATION",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_PSYCHIATRY: "State College Predictor-PG-DIPLOMA-IN-PSYCHIATRY",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_FORENSIC_MEDICINE: "State College Predictor-PG-DIPLOMA-IN-FORENSIC-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_ENT: "State College Predictor-PG-DIPLOMA-IN-ENT",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_DERMATOLOGY: "State College Predictor-PG-DIPLOMA-IN-DERMATOLOGY",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_RADIATION_MEDICINE: "State College Predictor-PG-DIPLOMA-IN-RADIATION-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MS_TRAUMATOLOGY_AND_SURGERY: "State College Predictor-PG-MS-TRAUMATOLOGY-AND-SURGERY",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_RADIOTHERAPY: "State College Predictor-PG-DIPLOMA-IN-RADIOTHERAPY",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_RADIOLOGY: "State College Predictor-PG-DIPLOMA-IN-RADIOLOGY",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_PUBLIC_HEALTH: "State College Predictor-PG-DIPLOMA-IN-PUBLIC-HEALTH",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_TB_AND_CHEST: "State College Predictor-PG-DIPLOMA-IN-TB-AND-CHEST",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_DIABETOLOGY: "State College Predictor-PG-DIPLOMA-IN-DIABETOLOGY",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_SPORTS_MEDICINE: "State College Predictor-PG-DIPLOMA-IN-SPORTS-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_BACTERIOLOGY: "State College Predictor-PG-DIPLOMA-IN-BACTERIOLOGY",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_TRANSFUSION_MEDICINE: "State College Predictor-PG-DIPLOMA-IN-TRANSFUSION-MEDICINE",
STATE_COLLEGE_PREDICTOR_PG_MCH_NEURO_SURGERY: "State College Predictor-PG-MCH-NEURO-SURGERY",
STATE_COLLEGE_PREDICTOR_PG_MD_COMMUNITY_HEALTH_ADMINSTRATION: "State College Predictor-PG-MD-COMMUNITY-HEALTH-ADMINSTRATION",
STATE_COLLEGE_PREDICTOR_PG_DIPLOMA_IN_HEALTH_ADMINISTRATION: "State College Predictor-PG-DIPLOMA-IN-HEALTH-ADMINISTRATION",





// MDS

 ALL_INDIA_COLLEGE_PREDICTOR_MDS_ALL: "All India College Predictor-MDS-ALL",

 ALL_INDIA_COLLEGE_PREDICTOR_MDS_ORAL_MEDICINE_AND_RADIOLOGY: "All India College Predictor-MDS-ORAL-MEDICINE-AND-RADIOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_MDS_ENDODONTICS: "All India College Predictor-MDS-ENDODONTICS",
 ALL_INDIA_COLLEGE_PREDICTOR_MDS_PUBLIC_HEALTH_DENTISTRY: "All India College Predictor-MDS-PUBLIC-HEALTH-DENTISTRY",
 ALL_INDIA_COLLEGE_PREDICTOR_MDS_PERIODONTOLOGY: "All India College Predictor-MDS-PERIODONTOLOGY",
 ALL_INDIA_COLLEGE_PREDICTOR_MDS_ORAL_AND_MAXILLOFACIAL_SURGERY: "All India College Predictor-MDS-ORAL-AND-MAXILLOFACIAL-SURGERY",
 ALL_INDIA_COLLEGE_PREDICTOR_MDS_PROSTHODONTICS: "All India College Predictor-MDS-PROSTHODONTICS",
 ALL_INDIA_COLLEGE_PREDICTOR_MDS_PEDODONTICS: "All India College Predictor-MDS-PEDODONTICS",
 ALL_INDIA_COLLEGE_PREDICTOR_MDS_ORTHODONTICS: "All India College Predictor-MDS-ORTHODONTICS",
 ALL_INDIA_COLLEGE_PREDICTOR_MDS_ORAL_PATHOLOGY_AND_MICROBIOLOGY: "All India College Predictor-MDS-ORAL-PATHOLOGY-AND-MICROBIOLOGY",
 
STATE_COLLEGE_PREDICTOR_MDS_ALL: "State College Predictor-MDS-ALL",

STATE_COLLEGE_PREDICTOR_MDS_ORAL_MEDICINE_AND_RADIOLOGY: "State College Predictor-MDS-ORAL-MEDICINE-AND-RADIOLOGY",
STATE_COLLEGE_PREDICTOR_MDS_ENDODONTICS: "State College Predictor-MDS-ENDODONTICS",
STATE_COLLEGE_PREDICTOR_MDS_PUBLIC_HEALTH_DENTISTRY: "State College Predictor-MDS-PUBLIC-HEALTH-DENTISTRY",
STATE_COLLEGE_PREDICTOR_MDS_PERIODONTOLOGY: "State College Predictor-MDS-PERIODONTOLOGY",
STATE_COLLEGE_PREDICTOR_MDS_ORAL_AND_MAXILLOFACIAL_SURGERY: "State College Predictor-MDS-ORAL-AND-MAXILLOFACIAL-SURGERY",
STATE_COLLEGE_PREDICTOR_MDS_PROSTHODONTICS: "State College Predictor-MDS-PROSTHODONTICS",
STATE_COLLEGE_PREDICTOR_MDS_PEDODONTICS: "State College Predictor-MDS-PEDODONTICS",
STATE_COLLEGE_PREDICTOR_MDS_ORTHODONTICS: "State College Predictor-MDS-ORTHODONTICS",
STATE_COLLEGE_PREDICTOR_MDS_ORAL_PATHOLOGY_AND_MICROBIOLOGY: "State College Predictor-MDS-ORAL-PATHOLOGY-AND-MICROBIOLOGY",


// DNB 

  ALL_INDIA_COLLEGE_PREDICTOR_DNB_ALL: "All India College Predictor-DNB-ALL",

  ALL_INDIA_COLLEGE_PREDICTOR_DNB_ANAESTHESIOLOGY: "All India College Predictor-DNB-ANAESTHESIOLOGY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_RADIODIAGNOSIS: "All India College Predictor-DNB-RADIODIAGNOSIS",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_GENERAL_SURGERY: "All India College Predictor-DNB-GENERAL-SURGERY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_ORTHOPAEDICS: "All India College Predictor-DNB-ORTHOPAEDICS",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_OBS_AND_GYNAE: "All India College Predictor-DNB-OBS-AND-GYNAE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_RADIATION_ONCOLOGY: "All India College Predictor-DNB-RADIATION-ONCOLOGY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PAEDIATRICS: "All India College Predictor-DNB-PAEDIATRICS",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_GENERAL_MEDICINE: "All India College Predictor-DNB-GENERAL-MEDICINE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_RADIODIAGNOSIS_DIPLOMA: "All India College Predictor-DNB-RADIODIAGNOSIS-DIPLOMA",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_ANAESTHESIOLOGY_DIPLOMA: "All India College Predictor-DNB-ANAESTHESIOLOGY-DIPLOMA",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_EMERGENCY_MEDICINE: "All India College Predictor-DNB-EMERGENCY-MEDICINE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_OPHTHALMOLOGY_DIPLOMA: "All India College Predictor-DNB-OPHTHALMOLOGY-DIPLOMA",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_NEURO_SURGERY: "All India College Predictor-DNB-NEURO-SURGERY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_OBS_AND_GYNAE_DIPLOMA: "All India College Predictor-DNB-OBS-AND-GYNAE-DIPLOMA",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_FAMILY_MEDICINE: "All India College Predictor-DNB-FAMILY-MEDICINE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_ENT: "All India College Predictor-DNB-ENT",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_OPHTHALMOLOGY: "All India College Predictor-DNB-OPHTHALMOLOGY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_FAMILY_MEDICINE_DIPLOMA: "All India College Predictor-DNB-FAMILY-MEDICINE-DIPLOMA",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PAEDIATRICS_DIPLOMA: "All India College Predictor-DNB-PAEDIATRICS-DIPLOMA",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_NUCLEAR_MEDICINE: "All India College Predictor-DNB-NUCLEAR-MEDICINE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_TB_AND_CHEST: "All India College Predictor-DNB-TB-AND-CHEST",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_TB_AND_CHEST_DIPLOMA: "All India College Predictor-DNB-TB-AND-CHEST-DIPLOMA",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PLASTIC_AND_RECONSTRUCTIVE_SURGERY: "All India College Predictor-DNB-PLASTIC-AND-RECONSTRUCTIVE-SURGERY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PATHOLOGY: "All India College Predictor-DNB-PATHOLOGY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_TRANSFUSION_MEDICINE: "All India College Predictor-DNB-TRANSFUSION-MEDICINE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_CARDIO_VASCULARAND_THORACIC_SURGERY: "All India College Predictor-DNB-CARDIO-VASCULARAND-THORACIC-SURGERY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_MICROBIOLOGY: "All India College Predictor-DNB-MICROBIOLOGY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PSYCHIATRY: "All India College Predictor-DNB-PSYCHIATRY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PHYSIOLOGY: "All India College Predictor-DNB-PHYSIOLOGY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_COMMUNITY_MEDICINE: "All India College Predictor-DNB-COMMUNITY-MEDICINE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PHARMACOLOGY: "All India College Predictor-DNB-PHARMACOLOGY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_DERMATOLOGY: "All India College Predictor-DNB-DERMATOLOGY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PALLIATIVE_MEDICINE: "All India College Predictor-DNB-PALLIATIVE-MEDICINE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PAEDIATRIC_SURGERY: "All India College Predictor-DNB-PAEDIATRIC-SURGERY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_GERIATRIC_MEDICINE: "All India College Predictor-DNB-GERIATRIC-MEDICINE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_BIOCHEMISTRY: "All India College Predictor-DNB-BIOCHEMISTRY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_FORENSIC_MEDICINE: "All India College Predictor-DNB-FORENSIC-MEDICINE",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_HOSPITAL_ADMINISTRATION: "All India College Predictor-DNB-HOSPITAL-ADMINISTRATION",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_PMR: "All India College Predictor-DNB-PMR",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_ANATOMY: "All India College Predictor-DNB-ANATOMY",
  ALL_INDIA_COLLEGE_PREDICTOR_DNB_EMERGENCY_MEDICINE_DIPLOMA: "All India College Predictor-DNB-EMERGENCY-MEDICINE-DIPLOMA",



  SINGLE_COLLEGE_CLOSING_RANK_UG: "Single College Closing Rank - UG",
  SINGLE_COLLEGE_CLOSING_RANK_PG: "Single College Closing Rank - PG",
  SINGLE_COLLEGE_CLOSING_RANK_MDS: "Single College Closing Rank - MDS",
  SINGLE_COLLEGE_CLOSING_RANK_SS: "Single College Closing Rank - SS",
  SINGLE_COLLEGE_CLOSING_RANK_DNB: "Single College Closing Rank - DNB",
  SINGLE_COLLEGE_CLOSING_RANK_INICET: "Single College Closing Rank - INICET",
  SINGLE_COLLEGE_CLOSING_RANK_AIAPGET: "Single College Closing Rank - AIAPGET",

  STATE_CLOSING_RANK_UG: "State Closing Rank - UG",
  STATE_CLOSING_RANK_PG: "State Closing Rank - PG",
  STATE_CLOSING_RANK_MDS: "State Closing Rank - MDS",
  STATE_CLOSING_RANK_SS: "State Closing Rank - SS",
  STATE_CLOSING_RANK_DNB: "State Closing Rank - DNB",
  STATE_CLOSING_RANK_INICET: "State Closing Rank - INICET",
  STATE_CLOSING_RANK_AIAPGET: "State Closing Rank - AIAPGET",

  ALL_INDIA_CLOSING_RANK_UG: "All India Closing Rank - UG",
  ALL_INDIA_CLOSING_RANK_PG: "All India Closing Rank - PG",
  ALL_INDIA_CLOSING_RANK_MDS: "All India Closing Rank - MDS",
  ALL_INDIA_CLOSING_RANK_SS: "All India Closing Rank - SS",
  ALL_INDIA_CLOSING_RANK_DNB: "All India Closing Rank - DNB",
  ALL_INDIA_CLOSING_RANK_INICET: "All India Closing Rank - INICET",
  ALL_INDIA_CLOSING_RANK_AIAPGET: "All India Closing Rank - AIAPGET",

  ALL_INDIA_CLOSING_RANK: "All India Closing Rank",

  PREMIUM_PLAN: "Plans",
}

